### ISSUE TITLE
Node-red config

### ISSUE THREAD

**Issue by Lars-the-tinkerer** [Langer75/volkswagencarnet-client#2]
Hey, very I'm interested to create a dashboard like yours when I get my PHEV in march. 
I'm already running node-red for other home automation projects and would love to incorporate this in it as well. Your dashboard looks perfect! Would you mind sharing the node-red flows file for that page? What library do you use for visuals, node red dashboard?

Thanks!

I'm very interested in the feature to limit amps while charging to balance my draw from the grid and to optimize for direct usage of solar panels. I already have the monitoring in place so its an easy thing to do! Have you played around with this? What is the range (0-16 amps) And the resolution? (just integer or can you go into more precise)

**Comment by Langer75** [comment]
Thank you. I have to think about how to share it.
>  What library do you use for visuals, node red dashboard?

Yes, node red dashboard

> I'm very interested in the feature to limit amps while charging to balance my draw from the grid and to optimize for direct usage of solar panels. I already have the monitoring in place so its an easy thing to do! Have you played around with this? What is the range (0-16 amps) And the resolution? (just integer or can you go into more precise)

Yes, I actually do PV-charging. The eGolf can handle more precise amp values. But not via the carnet communication to the car. So I get meter values every second from multicast of the meter device. The update to the wallbox will be done every 5 second, because the reaction of the car needs some seconds. The wallbox is controlled by evse-wifi. You can use the communication to the car only 15 times. Then you have to switch the clamp off/on for further 15 requests and so on. So it is not really useable for PV charging.

**Comment by Lars-the-tinkerer** [comment]
Thanks for your quick reply! I'm hyped to start once I receive my car :-) 

FYI: you can export the flows in JSON easily from node-red. It excludes database details and passwords. You can also choose which flows to export.

Too bad to hear that VWcarnet is that limiting. So only 15 updates per charging session? Then you have to switch a relay basicly? I was hoping to go this way for a year or so and then build my own car charger anyways based on EVSE indeed. Do you use this product for that purpose? https://www.evse-wifi.de/produkt/evse-wifi-2-0-base/. A limit with EV charger tech is that it doesn't want to go below 6 amps, I was hoping through VW carnet I could go to like 2Amp.

Huge thanks!

**Comment by Langer75** [comment]
what kind of car do you get? this carnet library will only work for the "old" VW cars based on the MQB like eGolf, eUp, Tiguan, Passat and so on. For the ID family the API is different. So you have to search for a working library and a working client for it. May be someone has developed some nodes for nodered.

You have 3 options: 
1. Buy the 2.0 Base (it is an 8GB version of ESP32)
2. Buy a ESP32 clone the repository and compile it for ESP32 4GB version
3. buy a ESP8266 and flash the precompiled version of EVSE wifi
I have chosed the second option.

Below 6A does not make sense because the car needs more for beeing waked up and starting the charging. So you need at least 6A to bring some energy into the battery. Below 6A the car will stop the caharging automatically.

**Comment by Lars-the-tinkerer** [comment]
Then I'm in luck! I'm getting a Tiguan eHybrid. 

I didn't know the car used that much in idle/ that rule. Then we'll have to account for it and switch some smaller devices when there is little solar. Here in Belgium we are also getting a peak usage based tariff we have to look out for so I'm going to implement everything in this project.

Thanks for outlining the options with the EVSE wifi! I'll have to research that sooner than planned.

**Comment by Langer75** [comment]
nothing more to discuss
